
name: "Teste de Action"
on:
    issues: 
        types: [opened]
    pull_request: 
        types: [opened]

jobs:
    teste-action-job-js:
        permissions: 
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: Execução de Custom Action (Composite)
        steps:
            - name: Adicionando Comentário
              id: comment_step
              uses: fsv-aula/action-composite@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário composite"
            - name: Mostrar o ID do comentário
              run: |
                echo 'ID do comentário é: ${{ steps.comment_step.outputs.comment-id }}'
