
name: "Teste de Action"
on:
    issues: 
        types: [opened]
    pull_request: 
        types: [opened]

jobs:
    teste-action-job-js:
        permissions: 
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        name: Execução de Custom Action (Docker)
        steps:
            - name: Adicionando Comentário
              id: comment_step
              uses: fsv-aula/action-docker@065033c8518f8168d94833c3a0f6d568239fb074
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                issue-id: ${{ github.event.issue.number }}
                comment: "Teste de comentário docker"
                GITHUB_REPOSITORY: ${{ github.repository }}
            - name: Mostrar o ID do comentário
              run: |
                echo 'ID do comentário é: ${{ steps.comment_step.outputs.comment-id }}'
